services:
  production:
    image: postgres:16-alpine
    container_name: production
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cdc_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data-postgres/pg5433:/var/lib/postgresql/data
      - ./config/pg5433/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/pg5433/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cdc_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  read_replica:
    image: postgres:16-alpine
    container_name: read_replica
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cdc_db
    ports:
      - "5434:5432"
    volumes:
      - ./init_replica.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data-postgres/pg5434:/var/lib/postgresql/data
      - ./config/pg5434/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./config/pg5434/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cdc_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      production:
        condition: service_healthy

  producer:
    build: ./producer_app
    environment:
      PG_HOST: production
      PG_PORT: "5432"
    depends_on:
      production:  { condition: service_healthy }
      read_replica: { condition: service_healthy }

  monitor:
    build: ./monitoring_app
    volumes:
      - ./monitoring_app/logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      production:  { condition: service_healthy }
      read_replica: { condition: service_healthy }

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "9092:9092"
    volumes:
      - ./data-kafka/kafka:/var/lib/kafka/data

  debezium:
    image: debezium/connect:3.0.0.Final
    container_name: debezium
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8083/"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "8083:8083"

  debezium-init:
    image: curlimages/curl:latest
    depends_on:
      debezium:
        condition: service_healthy
    volumes:
      - ./debezium.json:/connector.json:ro
    command: -s -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://debezium:8083/connectors/ --data @/connector.json

